name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Test Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.js
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true